FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY *.sln .
COPY DotNetTreeShadows/*.csproj ./DotNetTreeShadows/
RUN dotnet restore

FROM node:10.19.0 as clientBuild
WORKDIR /client
COPY ./DotNetTreeShadows/client/package.json .
RUN npm install
COPY ./DotNetTreeShadows/client .
RUN npm run build

FROM build-env as publish
COPY . ./
RUN dotnet publish -c Release -o out
COPY --from=clientBuild ./client/build ./DotNetTreeShadows/out/client/build

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=publish /app/DotNetTreeShadows/out ./

EXPOSE 80
EXPOSE 443
EXPOSE 5--
ENTRYPOINT ["dotnet", "DotNetTreeShadows.dll"]
