FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

ARG NODE_ENV
ARG TREE_SHADOWS_API_URL
ENV NODE_ENV=$NODE_ENV
ENV TREE_SHADOWS_API_URL=$TREE_SHADOWS_API_URL

RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs

FROM build AS compile
WORKDIR /src

COPY ["DotNetTreeShadows/DotNetTreeShadows.csproj", "DotNetTreeShadows/"]
RUN dotnet restore "DotNetTreeShadows/DotNetTreeShadows.csproj"
COPY . .
WORKDIR "/src/DotNetTreeShadows"
RUN dotnet build "DotNetTreeShadows.csproj" -c Release -o /app/build

FROM compile AS publish
RUN dotnet publish "DotNetTreeShadows.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY webserver.pfx .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "DotNetTreeShadows.dll"]